name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  nix-instantiate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - name: Check Nix parsing
        run: |
          find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +

  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check Nix formatting
        run: |
          nix run nixpkgs.nixpkgs-fmt -c nixpkgs-fmt --check .

  # TODO: https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md
  check-fully-featured-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: experimental-features = nix-command flakes
      - name: Run `nix flake check`
        run: cd examples/fully-featured && nix flake check --show-trace
      - name: Run `nix flake show`
        run: cd examples/fully-featured && nix flake show --show-trace
      - name: Build Morty configuration
        run: nix build .#nixosConfigurations.Morty.config.system.build.toplevel --dry-run
      - name: Build Rick configuration
        run: nix build .#nixosConfigurations.Rick.config.system.build.toplevel --dry-run

  check-somewhat-realistic-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: experimental-features = nix-command flakes
      - name: Run `nix flake check`
        run: cd examples/somewhat-realistic && nix flake check --show-trace
      - name: Run `nix flake show`
        run: cd examples/somewhat-realistic && nix flake show --show-trace
      - name: Build HostnameOne configuration
        run: nix build .#nixosConfigurations.HostnameOne.config.system.build.toplevel --dry-run
      - name: Build HostNameThree configuration
        run: nix build .#darwinConfigurations.HostNameThree.config.system.build.toplevel --dry-run

