name: CI
on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: experimental-features = nix-command flakes

      - name: Check Nix parsing
        run: find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +

      - name: Run `nix flake check`
        run: cd examples/fully-featured && nix flake check --show-trace

      - name: Run `nix flake show`
        run: cd examples/fully-featured && nix flake show --show-trace

      - name: Build Morty configuration
        run: cd examples/fully-featured && nix build .#nixosConfigurations.Morty.config.system.build.toplevel --dry-run

      - name: Build Rick configuration
        run: cd examples/fully-featured && nix build .#someConfigurations.Rick.config.system.build.toplevel --dry-run

      - name: Build Summer checks
        run: cd examples/fully-featured && nix build .#checks.x86_64-linux.summerHasUnfreeConfigured && nix build .#checks.x86_64-linux.summerHasPackageOverridesConfigured && nix build .#checks.x86_64-linux.summerHasCustomModuleConfigured

      - name: Run `nix flake check`
        run: cd examples/somewhat-realistic && nix flake check --show-trace

      - name: Run `nix flake show`
        run: cd examples/somewhat-realistic && nix flake show --show-trace

      - name: Build HostnameOne configuration
        run: cd examples/somewhat-realistic && nix build .#nixosConfigurations.HostnameOne.config.system.build.toplevel --dry-run

      - name: Check Nix formatting
        run: nix shell nixpkgs\#nixpkgs-fmt -c nixpkgs-fmt --check .

      - name: Build HostnameThree configuration
        run: cd examples/somewhat-realistic && nix build .#darwinConfigurations.HostnameThree.config.system.build.toplevel --dry-run

